#! /usr/bin/env bash

 #
 # Copyright (c) 2023 Project CHIP Authors
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 # http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.

set -e
cd /generator-output

CMDNAME=${0##*/}

usage() {
  exitcode="$1"
  cat <<USAGE >&2

Postprocess the output of openapi-generator

Usage:
  $CMDNAME -p PACKAGE_NAME

Options:
  -p, --package-name       The name to use for the generated package
  -h, --help               Show this message
USAGE
  exit "$exitcode"
}

main() {
  validate_inputs
  merge_generated_models
  delete_unused
  fix_any_of
  fix_optional_defaults
  fix_api_response_types
  apply_formatters
}

validate_inputs() {
  if [ -z "$PACKAGE_NAME" ]; then
    echo "Error: you need to provide --package-name argument"
    usage 2
  fi
}

merge_generated_models() {
  # Need to merge the generated models into a single file to prevent circular imports
  # shellcheck disable=SC2046
  # shellcheck disable=SC2010
  cat $(ls "${PACKAGE_NAME}"/models/*.py | grep -v __init__) >"${PACKAGE_NAME}"/models.py
  rm -r "${PACKAGE_NAME}"/models >/dev/null 2>&1 || true
}

delete_unused() {
  # Delete empty folder
  rm -r "${PACKAGE_NAME}"/test >/dev/null 2>&1 || true

  rm "${PACKAGE_NAME}"/rest.py >/dev/null 2>&1 || true
  rm "${PACKAGE_NAME}"/configuration.py >/dev/null 2>&1 || true
}

fix_any_of() {
  find . -name "*.py" -exec sed -i.bak "s/AnyOf[a-zA-Z0-9]*/Any/" {} \;
  find . -name "*.md" -exec sed -i.bak "s/AnyOf[a-zA-Z0-9]*/Any/" {} \;
  find . -name "*.bak" -exec rm {} \;
}

fix_optional_defaults() {
  echo "Fixing Optional/default value issues..."
  # The OpenAPI spec is copied to /generator-output/openapi-spec.json by openapi-generate.sh
  # The fix script is at /fix_optional_defaults.py (added by Dockerfile)
  # The models file is at models.py created by merge_generated_models()
  if [ -f "/generator-output/openapi-spec.json" ] && [ -f "/fix_optional_defaults.py" ]; then
    python3 /fix_optional_defaults.py \
      --openapi-spec /generator-output/openapi-spec.json \
      --models-file "${PACKAGE_NAME}/models.py"
    # Clean up the spec file after processing
    rm /generator-output/openapi-spec.json
  else
    echo "Warning: Could not find OpenAPI spec or fix script, skipping Optional/default fixes"
    echo "  - OpenAPI spec exists: $([ -f /generator-output/openapi-spec.json ] && echo 'yes' || echo 'no')"
    echo "  - Fix script exists: $([ -f /fix_optional_defaults.py ] && echo 'yes' || echo 'no')"
  fi
}

fix_api_response_types() {
  echo "Fixing api_response.py type annotations..."
  # The fix script is at /fix_api_response_types.py (added by Dockerfile)
  # The api_response.py file is generated by openapi-generator
  if [ -f "/fix_api_response_types.py" ] && [ -f "${PACKAGE_NAME}/api_response.py" ]; then
    python3 /fix_api_response_types.py \
      --api-response-file "${PACKAGE_NAME}/api_response.py"
  else
    echo "Warning: Could not find fix script or api_response.py, skipping api_response type fixes"
    echo "  - Fix script exists: $([ -f /fix_api_response_types.py ] && echo 'yes' || echo 'no')"
    echo "  - api_response.py exists: $([ -f ${PACKAGE_NAME}/api_response.py ] && echo 'yes' || echo 'no')"
  fi
}

apply_formatters() {
  echo "Applying code formatters to $PACKAGE_NAME..."
  autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place "${PACKAGE_NAME}" --exclude=__init__.py
  isort --float-to-top -w 120 -m 3 --trailing-comma --force-grid-wrap 0 --combine-as -p "${PACKAGE_NAME}" "${PACKAGE_NAME}"
  black --fast -l 120 --target-version py310 "${PACKAGE_NAME}"
  echo "All formatters applied."
}

while [ $# -gt 0 ]; do
  case "$1" in
  -p | --package-name)
    PACKAGE_NAME=$2
    shift 2
    ;;
  -h | --help)
    usage 0
    ;;
  *)
    echo "Unknown argument: $1"
    usage 1
    ;;
  esac
done

main
