# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-04-08T20:07:43+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Any

from pydantic import BaseModel, Field, RootModel


class ImportFile(RootModel[bytes]):
    root: Annotated[bytes, Field(title="Import File")]


class BodyImportTestRunExecutionApiV1TestRunExecutionsImportPost(BaseModel):
    import_file: Annotated[bytes, Field(title="Import File")]


class BodyImportprojectConfigApiV1ProjectsImportPost(BodyImportTestRunExecutionApiV1TestRunExecutionsImportPost):
    pass


class File(RootModel[bytes]):
    root: Annotated[bytes, Field(title="File")]


class BodyUploadFileApiV1TestRunExecutionsFileUploadPost(BaseModel):
    file: Annotated[bytes, Field(title="File")]


class BodyUploadPicsApiV1ProjectsIdUploadPicsPut(BodyUploadFileApiV1TestRunExecutionsFileUploadPost):
    pass


class ChipServerInfo(BaseModel):
    node_id: Annotated[int, Field(title="Node Id")]
    node_id_hex: Annotated[str, Field(title="Node Id Hex")]
    manual_pairing_code: Annotated[str | None, Field(title="Manual Pairing Code")] = None


class Msg(BaseModel):
    msg: Annotated[str, Field(title="Msg")]


class Name(RootModel[str]):
    root: Annotated[str, Field(title="Name")]


class Id(RootModel[int]):
    root: Annotated[int, Field(title="Id")]


class Operator(BaseModel):
    name: Annotated[str, Field(title="Name")]
    id: Annotated[int, Field(title="Id")]


class OperatorCreate(BaseModel):
    name: Annotated[str, Field(title="Name")]


class OperatorToExport(OperatorCreate):
    pass


class OperatorUpdate(BaseModel):
    name: Annotated[str | None, Field(title="Name")] = None


class PICSApplicableTestCases(BaseModel):
    test_cases: Annotated[list[str], Field(title="Test Cases")]


class PICSItem(BaseModel):
    number: Annotated[str, Field(title="Number")]
    enabled: Annotated[bool, Field(title="Enabled")]


class PublicId(RootModel[str]):
    root: Annotated[str, Field(title="Public Id")]


class Title(RootModel[str]):
    root: Annotated[str, Field(title="Title")]


class Description(RootModel[str]):
    root: Annotated[str, Field(title="Description")]


class Version(RootModel[str]):
    root: Annotated[str, Field(title="Version")]


class SourceHash(RootModel[str]):
    root: Annotated[str, Field(title="Source Hash")]


class Mandatory(RootModel[bool]):
    root: Annotated[bool, Field(title="Mandatory")] = False


class TestCaseMetadata(BaseModel):
    public_id: Annotated[str, Field(title="Public Id")]
    title: Annotated[str, Field(title="Title")]
    description: Annotated[str, Field(title="Description")]
    version: Annotated[str, Field(title="Version")]
    source_hash: Annotated[str, Field(title="Source Hash")]
    mandatory: Annotated[bool | None, Field(title="Mandatory")] = False
    id: Annotated[int, Field(title="Id")]


class TestCaseMetadataBase(BaseModel):
    public_id: Annotated[str, Field(title="Public Id")]
    title: Annotated[str, Field(title="Title")]
    description: Annotated[str, Field(title="Description")]
    version: Annotated[str, Field(title="Version")]
    source_hash: Annotated[str, Field(title="Source Hash")]
    mandatory: Annotated[bool | None, Field(title="Mandatory")] = False


class TestEnvironmentConfig(BaseModel):
    test_parameters: Annotated[dict[str, Any] | None, Field(title="Test Parameters")] = None


class TestHarnessBackendVersion(BaseModel):
    version: Annotated[str, Field(title="Version")]
    sha: Annotated[str, Field(title="Sha")]
    sdk_sha: Annotated[str, Field(title="Sdk Sha")]
    sdk_docker_tag: Annotated[str, Field(title="Sdk Docker Tag")]
    db_revision: Annotated[str, Field(title="Db Revision")]


class TestMetadata(BaseModel):
    public_id: Annotated[str, Field(title="Public Id")]
    version: Annotated[str, Field(title="Version")]
    title: Annotated[str, Field(title="Title")]
    description: Annotated[str, Field(title="Description")]
    mandatory: Annotated[bool | None, Field(title="Mandatory")] = False


class TestRunConfig(BaseModel):
    name: Annotated[str, Field(title="Name")]
    dut_name: Annotated[str, Field(title="Dut Name")]
    selected_tests: Annotated[dict[str, dict[str, dict[str, int]]] | None, Field(title="Selected Tests")] = {}
    id: Annotated[int, Field(title="Id")]


class TestRunConfigCreate(BaseModel):
    name: Annotated[str, Field(title="Name")]
    dut_name: Annotated[str, Field(title="Dut Name")]
    selected_tests: Annotated[dict[str, dict[str, dict[str, int]]] | None, Field(title="Selected Tests")] = {}


class TestRunConfigToExport(BaseModel):
    name: Annotated[str, Field(title="Name")]
    dut_name: Annotated[str, Field(title="Dut Name")]
    selected_tests: Annotated[dict[str, dict[str, dict[str, int]]] | None, Field(title="Selected Tests")] = {}
    created_at: Annotated[datetime, Field(title="Created At")]


class TestRunConfigUpdate(OperatorCreate):
    pass


class TestRunExecutionCreate(BaseModel):
    title: Annotated[str, Field(title="Title")]
    description: Annotated[str | None, Field(title="Description")] = None
    execution_config: Annotated[dict[str, Any] | None, Field(title="Execution Config")] = None
    execution_pics: Annotated[dict[str, Any] | None, Field(title="Execution Pics")] = None
    certification_mode: Annotated[bool | None, Field(title="Certification Mode")] = False
    test_run_config_id: Annotated[int | None, Field(title="Test Run Config Id")] = None
    project_id: Annotated[int | None, Field(title="Project Id")] = None
    operator_id: Annotated[int | None, Field(title="Operator Id")] = None


class TestRunExecutionStats(BaseModel):
    test_case_count: Annotated[int | None, Field(title="Test Case Count")] = 0
    states: Annotated[dict[str, int] | None, Field(title="States")] = {}


class TestRunLogEntry(BaseModel):
    level: Annotated[str, Field(title="Level")]
    timestamp: Annotated[float, Field(title="Timestamp")]
    message: Annotated[str, Field(title="Message")]
    test_suite_execution_index: Annotated[int | None, Field(title="Test Suite Execution Index")] = None
    test_case_execution_index: Annotated[int | None, Field(title="Test Case Execution Index")] = None
    test_step_execution_index: Annotated[int | None, Field(title="Test Step Execution Index")] = None


class TestRunnerState(Enum):
    idle = "idle"
    loading = "loading"
    ready = "ready"
    running = "running"


class TestRunnerStatus(BaseModel):
    state: TestRunnerState
    test_run_execution_id: Annotated[int | None, Field(title="Test Run Execution Id")] = None


class TestStateEnum(Enum):
    pending = "pending"
    executing = "executing"
    pending_actuation = "pending_actuation"
    passed = "passed"
    failed = "failed"
    error = "error"
    not_applicable = "not_applicable"
    cancelled = "cancelled"


class TestStepExecution(BaseModel):
    state: TestStateEnum
    title: Annotated[str, Field(title="Title")]
    execution_index: Annotated[int, Field(title="Execution Index")]
    id: Annotated[int, Field(title="Id")]
    test_case_execution_id: Annotated[int, Field(title="Test Case Execution Id")]
    started_at: Annotated[datetime | None, Field(title="Started At")] = None
    completed_at: Annotated[datetime | None, Field(title="Completed At")] = None
    errors: Annotated[list[str] | None, Field(title="Errors")] = None
    failures: Annotated[list[str] | None, Field(title="Failures")] = None


class TestStepExecutionToExport(BaseModel):
    state: TestStateEnum
    title: Annotated[str, Field(title="Title")]
    execution_index: Annotated[int, Field(title="Execution Index")]
    started_at: Annotated[datetime | None, Field(title="Started At")] = None
    completed_at: Annotated[datetime | None, Field(title="Completed At")] = None
    errors: Annotated[list[str] | None, Field(title="Errors")] = None
    failures: Annotated[list[str] | None, Field(title="Failures")] = None
    created_at: Annotated[datetime, Field(title="Created At")]


class TestSuiteMetadata(TestCaseMetadata):
    pass


class TestSuiteMetadataBase(TestCaseMetadataBase):
    pass


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class BodyCreateCliTestRunExecutionApiV1TestRunExecutionsCliPost(BaseModel):
    test_run_execution_in: TestRunExecutionCreate
    selected_tests: Annotated[dict[str, dict[str, dict[str, int]]], Field(title="Selected Tests")]
    execution_config: Annotated[dict[str, Any] | None, Field(title="Execution Config")] = None
    execution_pics: Annotated[dict[str, Any] | None, Field(title="Execution Pics")] = None


class BodyCreateTestRunExecutionApiV1TestRunExecutionsPost(BaseModel):
    test_run_execution_in: TestRunExecutionCreate
    selected_tests: Annotated[dict[str, dict[str, dict[str, int]]], Field(title="Selected Tests")]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class PICSCluster(BaseModel):
    name: Annotated[str, Field(title="Name")]
    items: Annotated[
        dict[str, PICSItem] | None, Field(default_factory=lambda: PICSItem.model_validate({}), title="Items")
    ]


class TestCase(BaseModel):
    metadata: TestMetadata


class TestCaseExecution(BaseModel):
    state: TestStateEnum
    public_id: Annotated[str, Field(title="Public Id")]
    execution_index: Annotated[int, Field(title="Execution Index")]
    id: Annotated[int, Field(title="Id")]
    test_suite_execution_id: Annotated[int, Field(title="Test Suite Execution Id")]
    test_case_metadata_id: Annotated[int, Field(title="Test Case Metadata Id")]
    started_at: Annotated[datetime | None, Field(title="Started At")] = None
    completed_at: Annotated[datetime | None, Field(title="Completed At")] = None
    errors: Annotated[list[str] | None, Field(title="Errors")] = None
    test_case_metadata: TestCaseMetadata
    test_step_executions: Annotated[list[TestStepExecution], Field(title="Test Step Executions")]


class TestCaseExecutionToExport(BaseModel):
    state: TestStateEnum
    public_id: Annotated[str, Field(title="Public Id")]
    execution_index: Annotated[int, Field(title="Execution Index")]
    started_at: Annotated[datetime | None, Field(title="Started At")] = None
    completed_at: Annotated[datetime | None, Field(title="Completed At")] = None
    errors: Annotated[list[str] | None, Field(title="Errors")] = None
    test_case_metadata: TestCaseMetadataBase
    test_step_executions: Annotated[list[TestStepExecutionToExport], Field(title="Test Step Executions")]
    created_at: Annotated[datetime, Field(title="Created At")]


class TestRunExecution(BaseModel):
    title: Annotated[str, Field(title="Title")]
    description: Annotated[str | None, Field(title="Description")] = None
    execution_config: Annotated[dict[str, Any] | None, Field(title="Execution Config")] = None
    execution_pics: Annotated[dict[str, Any] | None, Field(title="Execution Pics")] = None
    certification_mode: Annotated[bool | None, Field(title="Certification Mode")] = False
    test_run_config_id: Annotated[int | None, Field(title="Test Run Config Id")] = None
    project_id: Annotated[int | None, Field(title="Project Id")] = None
    id: Annotated[int, Field(title="Id")]
    state: TestStateEnum
    started_at: Annotated[datetime | None, Field(title="Started At")] = None
    completed_at: Annotated[datetime | None, Field(title="Completed At")] = None
    imported_at: Annotated[datetime | None, Field(title="Imported At")] = None
    archived_at: Annotated[datetime | None, Field(title="Archived At")] = None
    operator: Operator | None = None


class TestRunExecutionInDBBase(BaseModel):
    title: Annotated[str, Field(title="Title")]
    description: Annotated[str | None, Field(title="Description")] = None
    execution_config: Annotated[dict[str, Any] | None, Field(title="Execution Config")] = None
    execution_pics: Annotated[dict[str, Any] | None, Field(title="Execution Pics")] = None
    certification_mode: Annotated[bool | None, Field(title="Certification Mode")] = False
    test_run_config_id: Annotated[int | None, Field(title="Test Run Config Id")] = None
    project_id: Annotated[int | None, Field(title="Project Id")] = None
    id: Annotated[int, Field(title="Id")]
    state: TestStateEnum
    started_at: Annotated[datetime | None, Field(title="Started At")] = None
    completed_at: Annotated[datetime | None, Field(title="Completed At")] = None
    imported_at: Annotated[datetime | None, Field(title="Imported At")] = None
    archived_at: Annotated[datetime | None, Field(title="Archived At")] = None


class TestRunExecutionWithStats(BaseModel):
    title: Annotated[str, Field(title="Title")]
    description: Annotated[str | None, Field(title="Description")] = None
    execution_config: Annotated[dict[str, Any] | None, Field(title="Execution Config")] = None
    execution_pics: Annotated[dict[str, Any] | None, Field(title="Execution Pics")] = None
    certification_mode: Annotated[bool | None, Field(title="Certification Mode")] = False
    test_run_config_id: Annotated[int | None, Field(title="Test Run Config Id")] = None
    project_id: Annotated[int | None, Field(title="Project Id")] = None
    id: Annotated[int, Field(title="Id")]
    state: TestStateEnum
    started_at: Annotated[datetime | None, Field(title="Started At")] = None
    completed_at: Annotated[datetime | None, Field(title="Completed At")] = None
    imported_at: Annotated[datetime | None, Field(title="Imported At")] = None
    archived_at: Annotated[datetime | None, Field(title="Archived At")] = None
    operator: Operator | None = None
    test_case_stats: TestRunExecutionStats


class TestSuite(BaseModel):
    metadata: TestMetadata
    test_cases: Annotated[dict[str, TestCase], Field(title="Test Cases")]


class TestSuiteExecution(BaseModel):
    state: TestStateEnum
    public_id: Annotated[str, Field(title="Public Id")]
    execution_index: Annotated[int, Field(title="Execution Index")]
    collection_id: Annotated[str, Field(title="Collection Id")]
    mandatory: Annotated[bool | None, Field(title="Mandatory")] = False
    id: Annotated[int, Field(title="Id")]
    test_run_execution_id: Annotated[int, Field(title="Test Run Execution Id")]
    test_suite_metadata_id: Annotated[int, Field(title="Test Suite Metadata Id")]
    started_at: Annotated[datetime | None, Field(title="Started At")] = None
    completed_at: Annotated[datetime | None, Field(title="Completed At")] = None
    errors: Annotated[list[str] | None, Field(title="Errors")] = None
    test_case_executions: Annotated[list[TestCaseExecution], Field(title="Test Case Executions")]
    test_suite_metadata: TestSuiteMetadata


class TestSuiteExecutionToExport(BaseModel):
    state: TestStateEnum
    public_id: Annotated[str, Field(title="Public Id")]
    execution_index: Annotated[int, Field(title="Execution Index")]
    collection_id: Annotated[str, Field(title="Collection Id")]
    mandatory: Annotated[bool | None, Field(title="Mandatory")] = False
    started_at: Annotated[datetime | None, Field(title="Started At")] = None
    completed_at: Annotated[datetime | None, Field(title="Completed At")] = None
    errors: Annotated[list[str] | None, Field(title="Errors")] = None
    test_case_executions: Annotated[list[TestCaseExecutionToExport], Field(title="Test Case Executions")]
    test_suite_metadata: TestSuiteMetadataBase
    created_at: Annotated[datetime, Field(title="Created At")]


class PICS(BaseModel):
    clusters: Annotated[
        dict[str, PICSCluster] | None, Field(default_factory=lambda: PICSCluster.model_validate({}), title="Clusters")
    ]


class Project(BaseModel):
    name: Annotated[str, Field(title="Name")]
    config: Annotated[dict[str, Any] | None, Field(title="Config")] = None
    pics: Annotated[PICS | None, Field(default_factory=lambda: PICS.model_validate({"clusters": {}}), title="Pics")]
    id: Annotated[int, Field(title="Id")]
    created_at: Annotated[datetime, Field(title="Created At")]
    updated_at: Annotated[datetime, Field(title="Updated At")]
    archived_at: Annotated[datetime | None, Field(title="Archived At")] = None


class ProjectCreate(BaseModel):
    name: Annotated[str, Field(title="Name")]
    config: Annotated[dict[str, Any] | None, Field(title="Config")] = None
    pics: Annotated[PICS | None, Field(default_factory=lambda: PICS.model_validate({"clusters": {}}), title="Pics")]


class ProjectUpdate(BaseModel):
    name: Annotated[str | None, Field(title="Name")] = None
    config: Annotated[dict[str, Any] | None, Field(title="Config")] = None
    pics: PICS | None = None


class TestCollection(BaseModel):
    name: Annotated[str, Field(title="Name")]
    path: Annotated[str, Field(title="Path")]
    test_suites: Annotated[dict[str, TestSuite], Field(title="Test Suites")]


class TestCollections(BaseModel):
    test_collections: Annotated[dict[str, TestCollection], Field(title="Test Collections")]


class TestRunExecutionToExport(BaseModel):
    title: Annotated[str, Field(title="Title")]
    description: Annotated[str | None, Field(title="Description")] = None
    execution_config: Annotated[dict[str, Any] | None, Field(title="Execution Config")] = None
    execution_pics: Annotated[dict[str, Any] | None, Field(title="Execution Pics")] = None
    certification_mode: Annotated[bool | None, Field(title="Certification Mode")] = False
    state: TestStateEnum
    started_at: Annotated[datetime | None, Field(title="Started At")] = None
    completed_at: Annotated[datetime | None, Field(title="Completed At")] = None
    archived_at: Annotated[datetime | None, Field(title="Archived At")] = None
    test_suite_executions: Annotated[
        list[TestSuiteExecutionToExport] | None, Field(title="Test Suite Executions")
    ] = None
    created_at: Annotated[datetime, Field(title="Created At")]
    log: Annotated[list[TestRunLogEntry], Field(title="Log")]
    operator: OperatorToExport | None = None
    test_run_config: TestRunConfigToExport | None = None


class TestRunExecutionWithChildren(BaseModel):
    title: Annotated[str, Field(title="Title")]
    description: Annotated[str | None, Field(title="Description")] = None
    execution_config: Annotated[dict[str, Any] | None, Field(title="Execution Config")] = None
    execution_pics: Annotated[dict[str, Any] | None, Field(title="Execution Pics")] = None
    certification_mode: Annotated[bool | None, Field(title="Certification Mode")] = False
    test_run_config_id: Annotated[int | None, Field(title="Test Run Config Id")] = None
    project_id: Annotated[int | None, Field(title="Project Id")] = None
    id: Annotated[int, Field(title="Id")]
    state: TestStateEnum
    started_at: Annotated[datetime | None, Field(title="Started At")] = None
    completed_at: Annotated[datetime | None, Field(title="Completed At")] = None
    imported_at: Annotated[datetime | None, Field(title="Imported At")] = None
    archived_at: Annotated[datetime | None, Field(title="Archived At")] = None
    operator: Operator | None = None
    test_suite_executions: Annotated[list[TestSuiteExecution] | None, Field(title="Test Suite Executions")] = None


class ExportedTestRunExecution(BaseModel):
    db_revision: Annotated[str, Field(title="Db Revision")]
    test_run_execution: TestRunExecutionToExport
